In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np

In [2]:
dataset = pd.read_csv('dataset - fix.csv')
dataset.tail()

,class,name,age,total,grade,label,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
55,Responsible,yunita kesya,15,7,2,5,1,1,1,0,1,0,0,1,1,1,0,0,0,0,0,0
56,Integrity,muhammad irsan nurzaini,14,6,2,6,0,1,0,0,0,0,0,0,1,1,1,1,0,1,0,0
57,Enthusiastic,ghina ussaadah,10,3,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
58,Responsible,alfadhlan,12,1,2,5,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
59,Diligent,wulan,22,14,4,8,1,1,1,1,1,1,1,1,1,1,1,0,1,1,0,1

In [3]:
df = dataset[['age','total','grade','label']]
df.head()

   age  total  grade  label
0   17     15      3      8
1   25     14      4      8
2   24     14      4      8
3   18     14      3      8
4   10      1      1      3

In [4]:
x = df.drop(['label'], axis=1).values
y = df.label.values

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, random_state=42, stratify=y)
scale = MinMaxScaler()
x_train = scale.fit_transform(x_train)
x_test = scale.transform(x_test)
reg = RandomForestRegressor()
reg.fit(x_train, y_train)
y_pred = reg.predict(x_test)
score = r2_score(y_true=y_test, y_pred=y_pred)
print(score)

0.8553929563000239

In [6]:
from kebanyakan_model import tumpukan_regresi, tumpukan_klasifikasi, proses, regresi, klasifikasi

In [7]:
tumpukan_regresi(x, y, scaler='minmax')

                        Algorithm     Score Time
28                            SVR  0.867135   0s
27                          NuSVR  0.865731   0s
23            KNeighborsRegressor  0.856986   0s
4           RandomForestRegressor  0.856252   0s
3       GradientBoostingRegressor  0.849085   0s
29          DecisionTreeRegressor  0.834332   0s
0               AdaBoostRegressor  0.834317   0s
1                BaggingRegressor  0.811722   0s
2             ExtraTreesRegressor  0.787020   0s
26                      LinearSVR  0.774892   0s
12                           Lars  0.707251   0s
7                LinearRegression  0.707251   0s
25                   MLPRegressor  0.705128   0s
15                        LassoCV  0.696297   0s
13                         LarsCV  0.696153   0s
17                    LassoLarsCV  0.696153   0s
11                   ElasticNetCV  0.691771   0s
19                  BayesianRidge  0.686297   0s
18                  ARDRegression  0.679259   0s
8                           Ridge  0.674313   0s
9                         RidgeCV  0.674313   0s
5   HistGradientBoostingRegressor  0.620079   1s
20               PoissonRegressor  0.418126   0s
24       RadiusNeighborsRegressor  0.380679   0s
21               TweedieRegressor  0.188518   0s
22                 GammaRegressor  0.180916   0s
14                          Lasso -0.000107   0s
16                      LassoLars -0.000107   0s
10                     ElasticNet -0.000107   0s
6        GaussianProcessRegressor -4.769630   0s

In [8]:
x_train, x_test, y_train, y_test = proses(x, y, scaler='minmax')

In [9]:
regresi(x_train, x_test, y_train, y_test, 'nu_svr').round(2)

0.87